//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""RTSController"",
            ""id"": ""ed72175b-ab2d-4733-99cb-8bb13693b0b4"",
            ""actions"": [
                {
                    ""name"": ""2DOverlay"",
                    ""type"": ""Button"",
                    ""id"": ""d2e7a02f-c563-4210-a1a8-9772d6118df0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""09df4144-0f63-46a9-bec1-28406fbfa350"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2DOverlay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RTSController
        m_RTSController = asset.FindActionMap("RTSController", throwIfNotFound: true);
        m_RTSController__2DOverlay = m_RTSController.FindAction("2DOverlay", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RTSController
    private readonly InputActionMap m_RTSController;
    private List<IRTSControllerActions> m_RTSControllerActionsCallbackInterfaces = new List<IRTSControllerActions>();
    private readonly InputAction m_RTSController__2DOverlay;
    public struct RTSControllerActions
    {
        private @PlayerInputActions m_Wrapper;
        public RTSControllerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @_2DOverlay => m_Wrapper.m_RTSController__2DOverlay;
        public InputActionMap Get() { return m_Wrapper.m_RTSController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RTSControllerActions set) { return set.Get(); }
        public void AddCallbacks(IRTSControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_RTSControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RTSControllerActionsCallbackInterfaces.Add(instance);
            @_2DOverlay.started += instance.On_2DOverlay;
            @_2DOverlay.performed += instance.On_2DOverlay;
            @_2DOverlay.canceled += instance.On_2DOverlay;
        }

        private void UnregisterCallbacks(IRTSControllerActions instance)
        {
            @_2DOverlay.started -= instance.On_2DOverlay;
            @_2DOverlay.performed -= instance.On_2DOverlay;
            @_2DOverlay.canceled -= instance.On_2DOverlay;
        }

        public void RemoveCallbacks(IRTSControllerActions instance)
        {
            if (m_Wrapper.m_RTSControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRTSControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_RTSControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RTSControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RTSControllerActions @RTSController => new RTSControllerActions(this);
    public interface IRTSControllerActions
    {
        void On_2DOverlay(InputAction.CallbackContext context);
    }
}
